default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pratico_development

test:
  <<: *default
  database: pratico_test

production:
  <<: *default
  database: pratico_production
  username: pratico
  password: <%= ENV['PRATICO_DATABASE_PASSWORD'] %>
